### ISSUE TITLE
App description draft for review

### ISSUE THREAD

**Issue by sukhleen999** [UBC-MDS/gapminderdash-python-g14#4]
Hey team, I have written the app description for the README.md file and would be happy to incorporate suggested changes per your review.

**Description:**

The main objective of this project is to build a Python application using Dash, that visualizes key parametric indicators of the [Gapminder dataset](https://www.gapminder.org/data/). Users can leverage the dashboard to examine trends exhibited by the socioeconomic metrics of the dataset across countries and/or continents over a specified time range.

The app summarizes crucial information of the Gapminder dataset through illustrative plots that visualize the distribution of the dataset variables. The interface is designed to be interactive to make the app adaptive to the user input. The default view of the dashboard is comprised of a chloropleth map (which discloses the country on hover), a time series plot, a scatterplot, a bar chart and a summary table. In addition, the landing page also displays high level summary statistics such as the highest and lowest GDP per capita, population and life expectancy for the default selection. To further analyze the features of our data, the dashboard offers filters in the form of drop-down lists and tabs to draw meaningful insights specific to a particular continent, country, year or metric (Life expectancy, GDP per capita). Users can also analyze the global standing of countries in their continent (given by a continental summary table) and review top 5 countries for the selected metric and time range (in a bar chart).

The dashboard can be of significant use for consumers who wish to identify systematic misconceptions about important global trends/ proportions and examine how they evolved over the years.

**Comment by Amirshoja** [comment]
Thank you so much, this is a very good description.

**Comment by LukeAC** [comment]
Hi Sukhleen, looks great to me! Only thing that I caught was 'key parametric indicators': if you're referring to 'KPI' here, this should be 'key performance indicators'. :)

**Comment by sukhleen999** [comment]
Thanks Luke, I'll make the change.
