### ISSUE TITLE
Mockup first draft

### ISSUE THREAD

**Issue by Amirshoja** [UBC-MDS/gapminderdash-python-g14#5]
Hi team,
I have created the first draft of our dashboard mockup.
I have tried to include all the features we discussed and even added a collapsible sidebar to serve as a help bar to include instructions and guides to better work with the dashboard.

link to mockup image:
[dashboard-mockup-v1](https://github.com/UBC-MDS/gapminderdash-python-g14/blob/docs-mockup/dashboard-mockup-v1.jpg)

Please let me know if any changes are required.
Thanks

**Comment by sukhleen999** [comment]
This looks great! Thanks for building it :)
