### ISSUE TITLE
Suggested changes

### ISSUE THREAD

**Issue by sukhleen999** [UBC-MDS/gapminderdash-python-g14#7]
Hey team, I noticed a few things in the following files which might need to be changed:

- Contributing.md has a TODO part, are we supposed to remove it?
- Code_of_conduct.md has the wrong email address.

Please let me know your thoughts and I'll make the changes.

**Comment by Amirshoja** [comment]
Hi @sukhleen999 ,
Thanks for noticing, I think you are correct and those should be changed.

Thank you
